// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using reframe.Data;
using reframe.Models;

#nullable disable

namespace reframe.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260212215305_AddMasterQuestionnaireLink")]
    partial class AddMasterQuestionnaireLink
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("reframe.Models.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("End")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PsychologistId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<DateTime>("Start")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("PsychologistId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("reframe.Models.AutomaticThought", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AlternativeThoughts")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Behavior")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Emotion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EvidenceContra")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EvidencePro")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reevaluation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Situation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Thought")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("AutomaticThoughts");
                });

            modelBuilder.Entity("reframe.Models.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<List<PatientDocument>>("Documents")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("PendingPsychologistId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PsychologistId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PendingPsychologistId");

                    b.HasIndex("PsychologistId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("reframe.Models.Psychologist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BusinessPhone")
                        .HasColumnType("text");

                    b.Property<string>("CRP")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PresentationText")
                        .HasColumnType("text");

                    b.Property<int?>("SessionDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Specialty")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CRP")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Psychologists");
                });

            modelBuilder.Entity("reframe.Models.Questionnaire", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsShared")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("MasterQuestionnaireId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PsychologistId")
                        .HasColumnType("uuid");

                    b.Property<List<Question>>("Questions")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("TargetPatientId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PsychologistId");

                    b.HasIndex("TargetPatientId");

                    b.ToTable("Questionnaires");
                });

            modelBuilder.Entity("reframe.Models.QuestionnaireResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<List<Answer>>("Answers")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuestionnaireId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("QuestionnaireId");

                    b.ToTable("QuestionnaireResponses");
                });

            modelBuilder.Entity("reframe.Models.QuestionnaireTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsGlobal")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("OriginalPsychologistId")
                        .HasColumnType("uuid");

                    b.Property<List<Question>>("Questions")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("QuestionnaireTemplates");
                });

            modelBuilder.Entity("reframe.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AddressComplement")
                        .HasColumnType("text");

                    b.Property<string>("AddressNumber")
                        .HasColumnType("text");

                    b.Property<int?>("BiologicalSex")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Cpf")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Neighborhood")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("text");

                    b.Property<string>("ResetToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResetTokenExpires")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .HasColumnType("text");

                    b.Property<int>("UserType")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ZipCode")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("reframe.Models.Appointment", b =>
                {
                    b.HasOne("reframe.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("reframe.Models.Psychologist", "Psychologist")
                        .WithMany()
                        .HasForeignKey("PsychologistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("Psychologist");
                });

            modelBuilder.Entity("reframe.Models.AutomaticThought", b =>
                {
                    b.HasOne("reframe.Models.Patient", "Patient")
                        .WithMany("AutomaticThoughts")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("reframe.Models.Patient", b =>
                {
                    b.HasOne("reframe.Models.Psychologist", "PendingPsychologist")
                        .WithMany()
                        .HasForeignKey("PendingPsychologistId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("reframe.Models.Psychologist", "Psychologist")
                        .WithMany("Patients")
                        .HasForeignKey("PsychologistId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("reframe.Models.User", "User")
                        .WithOne("PatientProfile")
                        .HasForeignKey("reframe.Models.Patient", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PendingPsychologist");

                    b.Navigation("Psychologist");

                    b.Navigation("User");
                });

            modelBuilder.Entity("reframe.Models.Psychologist", b =>
                {
                    b.HasOne("reframe.Models.User", "User")
                        .WithOne("PsychologistProfile")
                        .HasForeignKey("reframe.Models.Psychologist", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("reframe.Models.Questionnaire", b =>
                {
                    b.HasOne("reframe.Models.Psychologist", "Psychologist")
                        .WithMany()
                        .HasForeignKey("PsychologistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("reframe.Models.Patient", "TargetPatient")
                        .WithMany()
                        .HasForeignKey("TargetPatientId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Psychologist");

                    b.Navigation("TargetPatient");
                });

            modelBuilder.Entity("reframe.Models.QuestionnaireResponse", b =>
                {
                    b.HasOne("reframe.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("reframe.Models.Questionnaire", "Questionnaire")
                        .WithMany()
                        .HasForeignKey("QuestionnaireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("Questionnaire");
                });

            modelBuilder.Entity("reframe.Models.Patient", b =>
                {
                    b.Navigation("AutomaticThoughts");
                });

            modelBuilder.Entity("reframe.Models.Psychologist", b =>
                {
                    b.Navigation("Patients");
                });

            modelBuilder.Entity("reframe.Models.User", b =>
                {
                    b.Navigation("PatientProfile");

                    b.Navigation("PsychologistProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
